global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["app:2019"]

  - job_name: app
    metrics_path: /metrics
    authorization:
      credentials_file: /tmp/metrics_token
    static_configs:
      - targets: ["app:9113"]
