global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: caddy
    static_configs:
      - targets: ["app:2019"]

  - job_name: app
    metrics_path: /metrics
    scheme: https
    tls_config:
      insecure_skip_verify: true
    authorization:
      credentials_file: /tmp/metrics_token
    static_configs:
      - targets: ["app:443"]
